### ISSUE TITLE
Ability to 'see' headers defined in RAML

### ISSUE THREAD

**Issue by scordatura** [cybertk/abao#24]
We can specify headers in RAML, for example:

```
resourceTypes:
  - collection-item:
      description: | 
        GET shows an individual <<resourcePathName|!singularize>>
      get:
        description: Get a list of <<resourcePathName>>.
        headers: &commonHeaders
          accept: 
            displayName: Accept
            description: MIME types that client is willing to accept.
            example: "*/*"
          content-type: 
            displayName: Content Type
            description: MIME type of document being served.
            example: "application/x-www-form-urlencoded,application/json"
```
...then later on:

```
/lakes/{id}:
    description: |  
      A collection of descriptions of the deepest lakes in the world.
    uriParameters:
      id:
        description: |
          A two-digit integer that serves as the ID of a lake. For example, 01 is the ID for Lake Baikal.
        type: integer
        example: 01
    type:
      collection-item:
        exampleItem: !include lakes-item.sample
    get:
      headers: *commonHeaders
```

Version 0.2.5 of Abao does not 'see' these headers. We are forced to specify the headers at the command line:

```
abao api.raml https://lakes-api.example.com -h 'Accept:*/*' -h 'Content-Type:application/x-www-form-urlencoded,application/json' --hookfiles=hook.coffee

```

**Note:** There is more than one way to specify headers in RAML. The syntax shown above is just one way.

Please improve Abao by adding the ability to 'see' the headers specified in the RAML, so that we can stop specifying headers at the command line. Thanks!
